### ISSUE TITLE
User Stories for Front End

### ISSUE THREAD

**Issue by RangerMauve** [hyphacoop/open-archive-dweb-backend#13]
## Initial access

- A new user wants to use the dweb backend.
- Navigate to the backends list, open up dweb backend
- See list of existing groups or create/join a group

## Create group

-User wants to make a new group
- They click "create" in the dweb screen
- Specify a name
- Group will have a "key" it's identified by, take the first few bytes along with the name to show to 
the user (maybe different color badges?)
- Group will have an "invite" view with a copyable link and a QR code representing that link.
- Use `save+veilid://` as the URL scheme and register the app to open to a group view based on the link

### Join existing group from link

- User doesn't want to make a new group but got a link from a friend
- Clicking the link should bring up save app in the "Join group" screen.
- This will show the group name and the number of members within it
- When they click the "Join" button the group will be added to their groups list and the proper group view will display
- If they got a link to a group they already had, show the group.

### Join existing group from QR code

- User 1 wants to onboard User 2
- User 1 navigates to the share screen
- User 2 scans the app with a qr code reader (e.g. default camera app)
- User 2 gets the link from the qr code and follows the flow from above

### View group / use files

- User clicks on one of the groups in the list of dweb groups
- The screen shows them the list of members in the group
- Clicking a member shows a screen with the list of files they're sharing
- Loading indicator as the file list gets fetched, also loading indicator when there's updates happening behind the scenes
- Status indicator beside file saying whether it's saved locally, exists with a peer, or no copy exists
- Clicking a file results in a download progress indicator (like a percentage?)
- Send a local notification to the phone upon completion
- Clicking a downloaded file will export it from the app

### Adding your own files

- When viewing the group, if the user had "write access" they will have a button to "start sharing"
- This will open a screen that lets them pick a name to show to the group as well as some info on what sharing to the dweb means
- Once they've joined their own name will show up as an item at the top of the list in the group
- There will be a list of files same as when viewing another user, but swiping to the side (or clicking a button or whatever) will delete the file
- There will also be an "add file" button at the bottom which will open the system file picker
- Long pressing on the file should trigger a text edit box to show up for renaming the file

## Todo:

- [ ] Mock up necessary screens for user stories. Post links / screenshots here
- [ ] Implement connections between the screens with fake data in the app
- [ ] Document all the expected "backend API calls" we'll need to enable the screens

**Comment by RangerMauve** [comment]
Aiming to start next week

**Comment by writerly03** [comment]
Richard estimates that Android can be done by Thursday. iOS to follow and will be done by mid-next week. This gives us 2 weeks to add the backend in and do testing.

**Comment by writerly03** [comment]
New date for this is eod Friday August 2

**Comment by rapuckett** [comment]
Initial screenshots of Veilid UX
![veilid_1](https://github.com/user-attachments/assets/fb702ba5-d7c6-424e-93ce-2d0619fee935)
![veilid_2](https://github.com/user-attachments/assets/06917a58-d599-4863-92c4-f70609588d21)

**Comment by writerly03** [comment]
Need screen shots for viewing a group, adding files, and listing existing files still

**Comment by RangerMauve** [comment]
Going in favor of new issues
